name: 'Deploy'

on:
  workflow_dispatch:

jobs:
  deploy:
    environment:
      name: staging

    runs-on: ubuntu-latest

    steps:
      - run: echo ${{ GITHUB_ACTOR }}
      - uses: actions/checkout@v3.0.0
      - run: echo 'hogehoge'
