name: 'Deploy'

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    # この設定は作業ブランチであっても外しちゃだめです
    if: github.ref == 'refs/heads/main'

    steps:
      - run: echo $GITHUB_ACTOR
      - uses: actions/checkout@v3.0.0
      - run: echo 'hogehoge'
