name: 'Deploy'

on:
  workflow_dispatch:

# この設定は作業ブランチであっても外しちゃだめです
if: github.ref == 'refs/heads/main'

jobs:
  deploy:
    environment:
      name: staging

    runs-on: ubuntu-latest

    steps:
      - run: echo $GITHUB_ACTOR
      - uses: actions/checkout@v3.0.0
      - run: echo 'hogehoge'
