name: 'Deploy'

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    # deploy workflowの処理はmainブランチにマージされたものしか利用できないようにしています
    # これは本来environmentsを利用してreviewステップを入れたいが契約がGithub Enterpriseではないのでそれができず、仕方なしのworkaroundです
    # ref https://stackoverflow.com/questions/69260199/is-there-a-way-to-restrict-what-branch-an-action-can-be-run-on
    # 事故を起こさないためにもこの設定は作業ブランチ上でも外さないようお願いします
    # if: github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v3.0.0
      - run: |
          pwd
          echo $GITHUB_ACTOR
          cd .github/workflows
          jq '.deployable_users | any(. == "$GITHUB_ACTOR")' ./deployable_users.json
