name: 'Deploy'

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    # deploy workflowの処理はmainブランチにマージされたものしか利用できないようにしています
    # これは本来environmentsを利用してreviewステップを入れたいが契約がGithub Enterpriseではないのでそれができず、仕方なしのworkaroundです
    # ref https://stackoverflow.com/questions/69260199/is-there-a-way-to-restrict-what-branch-an-action-can-be-run-on
    # 事故を起こさないためにもこの設定は作業ブランチ上でも外さないようお願いします
    # if: github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v3.0.0
      - run: |
          cd .github/workflows
          IS_DEPLOYABLE_USER=$(jq --arg ga $GITHUB_ACTOR '.deployable_users | any(. == $ga)' ./deployable_users.json)
          [ $IS_DEPLOYABLE_USER != "true" ] && exit 1
          echo 'ここにはきてほしくない'
